# Configure a default setup of Home Assistant (frontend, api, etc)
#default_config:
config:
frontend:
system_health:
zeroconf:

http:
  server_port: 8124

recorder:
  purge_keep_days: 0
  include:
    domains:
    entities:

discovery:
  ignore:
    - philips_hue
    - nanoleaf